apiVersion: v1
kind: Service
metadata:
  name: siemens-configurator-service
  namespace: default
spec:
  selector:
    app: siemens-configurator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: ClusterIP
